### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by stoyicker** [stoyicker/auto-factory-kotlin#1]
- [x] Replace the test output folder in the CircleCI yaml
- [x] Replace properties in dependencies ("a.b.c" -> rootProject."a.b.c")
- [ ] The accessor of the generated class should be the same as the class annotated (or the target class of the typealias)
- [x] Throw an error if the same class that is annotated also has one or more of its constructors annotated
- [x] License
- [ ] Respect qualifiers in arguments
- [ ] Create Generated
- [ ] Annotating a class works
- [ ] Annotating a typealias works
- [ ] Respect default parameters
- [ ] Generics in class definition and constructor. Also respect parameters with generics.
- [x] Tests
